---
name: Check style
'on':
  - push
  - pull_request
jobs:
  style:
    defaults:
      run:
        shell: 'bash -l {0}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1
          show-progress: false
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14.0
      - name: Install shellcheck and checkbashisms
        run: |
          sudo apt -yqq update
          sudo apt install -yqq perltidy shfmt shellcheck devscripts
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Show diagnostics
        run: make showvars
      - name: Check style
        run: make style-check
